### ISSUE TITLE
Lattice iCE40HX8K-BG121 121-ball caBGA

### ISSUE THREAD

**Issue by whitequark** [whitequark/Glasgow#28]

**Comment by awygle** [comment]
Kicad footprint PR: https://github.com/KiCad/kicad-footprints/pull/693
The symbol exists at https://github.com/awygle/kicad-symbols/tree/ice40hx but is waiting on https://github.com/KiCad/kicad-symbols/pull/457 to merge before creating the PR.

**Comment by whitequark** [comment]
@awygle That symbol is now merged.

**Comment by awygle** [comment]
Kicad symbol PR: https://github.com/KiCad/kicad-symbols/pull/777

**Comment by whitequark** [comment]
Symbol merged.
