### ISSUE TITLE
Use a dedicated USB protection IC instead of a regular fast-blow fuse

### ISSUE THREAD

**Issue by whitequark** [whitequark/Glasgow#34]
If you short Vio to GND for like a millisecond it blows instantly. Source: shorted Vio to GND for like a millisecond.

**Comment by whitequark** [comment]
This fuse will take ~1s to trip at 1A fault current. Seems completely pointless.

We need a fuse that will blow if you short the 3V3 supply to ground, but also will sustain short-circuit current of both LDOs indefinitely. This needs measurement and experimentation...

**Comment by awygle** [comment]
Per IRC discussion, will use http://www.ti.com/lit/ds/symlink/tpd3s014.pdf instead.

**Comment by whitequark** [comment]
This seems simple enough we really should add this in revB.

**Comment by awygle** [comment]
Closed by 369968e
