### ISSUE TITLE
Slew rate limiting resistors

### ISSUE THREAD

**Issue by whitequark** [whitequark/Glasgow#35]
Two arrays of four resistors per port. I'm not sure yet what the values should be; worst case, we can always populate with 0R and decide later.

**Comment by whitequark** [comment]
This will also add some very limited pin overcurrent protection. Say at 200 ohm, the buffers should tolerate ±10V on up to two signal pins (not Vio or Vsense though).

**Comment by whitequark** [comment]
0402 8-position array fits better (it's about the same size as FXMA108).

**Comment by whitequark** [comment]
Pretty sure we also need slew rate limiting on the *other* side of the level shifter because switching many inputs at once causes [glitches](https://github.com/whitequark/Glasgow/blob/a89f5a224449ddd5d1bf9e5f4e8b7e3bc2593bce/software/glasgow/gateware/fx2.py#L141-L145) on the FLAGn pins on the other side of the board. The apparently random timing of the glitches seems to suggest that glitches happen when the inputs transition happens closely enough to IFCLK transition.

**Comment by awygle** [comment]
I added these in commit 7c3203c126e7444981d5405d7d6fcd1db53bbbc5

**Comment by whitequark** [comment]
Thanks!
