### ISSUE TITLE
Make SYNC pullup smaller

### ISSUE THREAD

**Issue by whitequark** [whitequark/Glasgow#51]
The FPGA has ridiculously powerful drivers (what, 10 mA?) so if we use a pullup smaller than 1k we can go well into MHz range. Useful, because the PLL has a minimum frequency of 16 MHz--can we get that high?

**Comment by awygle** [comment]
I think 300 Ohms is the lowest we can safely go. That'll give us 300 mV of rise above ground at 3.3V with 10 mA drivers.

**Comment by whitequark** [comment]
It's actually 24 mA. On the other hand, Vil(max) for LVCMOS 3.3 inputs is 0.8 V, so 0.3 V seems fine.

**Comment by awygle** [comment]
Okay, that'd give us 125 Ohms. 130 for ease of sourcing. Math math math.

**Comment by whitequark** [comment]
Can you verify that this value actually gives a decent signal? I don't have my resistor set at hand...

**Comment by awygle** [comment]
I have some 120 Ohm resistors, I can look at what those give.

**Comment by awygle** [comment]
Where'd you find 24 mA as the value? I'm looking at 
![image](https://user-images.githubusercontent.com/7854806/41825600-fbc49328-77d6-11e8-8c1f-b75f46215081.png) and reading 8 mA.

(Just for completeness that's 375 Ohms by math and probably 390 by sourcing)

**Comment by whitequark** [comment]
Hrm, I might have been looking at the wrong package. 300 mV rise seems pretty low too, that's not enough to sync using e.g. external LMVCMOS 3.3 circuitry... Let's aim at 800 mV rise above ground then.

**Comment by awygle** [comment]
Because it's an open drain output, 300 mV is Voh in this case - the voltage for a logic 0. The high voltage will be the full VIO voltage.

**Comment by whitequark** [comment]
Oh right, I derped. That's fine then, let's go with 300 mV.

**Comment by awygle** [comment]
Whoops:

![image](https://user-images.githubusercontent.com/7854806/43041769-171a333c-8d1f-11e8-841b-cbf445adaeeb.png)
